name: phone_form_field
description: Flutter phone input integrated with flutter internationalization
version: 0.0.6
author: cedvdb
homepage: https://github.com/cedvdb/phone_form_field

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter
  circle_flags: ^0.0.2
  phone_numbers_parser: ^0.0.5
  font_awesome_flutter: ^9.0.0
  

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  assets:
    - assets/translations/

